### ISSUE TITLE
teamlinker - mysql error: Error: connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by linux-8** [Teamlinker/Teamlinker#7]
[2024-01-23T11:03:03.700] [ERROR] teamlinker - mysql error: Error: connect ECONNREFUSED 127.0.0.1:3306
    at PromisePool.query (/snapshot/dist/server/node_modules/mysql2/promise.js:341:22)
    at Mysql.executeOne (/snapshot/dist/server/common/db/mysql.js:52:41)
    at checkIfNeedInit (/snapshot/dist/server/gateway/util/util.js:210:31)
    at GateWay.config (/snapshot/dist/server/gateway/app/app.js:51:40)
    at Server.<anonymous> (/snapshot/dist/server/common/app/app.js:72:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ECONNREFUSED',
  errno: -111,
  sql: undefined,
  sqlState: undefined,
  sqlMessage: undefined
} select * from version;
[2024-01-23T11:03:03.729] [INFO] teamlinker - exec sql start
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}

Node.js v18.5.0

**Comment by xbdsky** [comment]
你的mysql服务配置错误，没正确连接

**Comment by linux-8** [comment]
> 你的mysql服务配置错误，没正确连接

那我应该怎么做，怎么排错？请您指点

**Comment by AgustinCrow** [comment]
Hi linux-8, pudiste resolverlo ?

**Comment by AgustinCrow** [comment]
Hi linux-8, were you able to solve it?

**Comment by sx1989827** [comment]
@AgustinCrow  you should check your mysql address in extra.config.json,if you are using docker,you should make sure the MySQL address is the  LAN address
